use QLSuaChuaXe3
go
---------------------View---------------------------
CREATE VIEW VIEW_NHAPKHO AS
SELECT NHAPKHO.MaNKho,VATLIEU.TenVL,NHACUNGCAP.TenNhaCC,NHAPKHO.SoLuong,NHAPKHO.GiaTri,NHAPKHO.NgayNhap,NHAPKHO.MaNV
FROM NHAPKHO,VATLIEU,NHACUNGCAP
WHERE NHAPKHO.MaVL=VATLIEU.MaVL AND NHAPKHO.MaNhaCC=NHACUNGCAP.MaNhaCC
GO
CREATE VIEW HOPDONG_REPORT AS
SELECT HOPDONG.SoHD,NgayHD,KH_NguoiID,SoXE, TriGiaHD, NgayGiaoDuKien, NgayNghiemThu,MaCV, TriGiaCV, MaNV
FROM HOPDONG, CHITIET_HD
where HOPDONG.SoHD = CHITIET_HD.SoHD

GO
CREATE VIEW VIEW_CVIEC AS
SELECT MaCViec, NoiDungCV,TienCong,TenVL
FROM CONGVIEC,VATLIEU
WHERE CONGVIEC.VatLieu=VATLIEU.MaVL
go

CREATE VIEW VIEW_NV AS
SELECT dbo.NHANVIEN.NV_NguoiID, dbo.TT_NGUOI.Hoten, dbo.TT_NGUOI.DiaChi, dbo.TT_NGUOI.DienThoai, dbo.TT_NGUOI.NgaySinh, 
	   dbo.TT_NGUOI.CCCD, dbo.TT_NGUOI.GioiTinh, dbo.CHUCVU.TenCV, dbo.NHANVIEN.Luong
FROM dbo.NHANVIEN INNER JOIN dbo.TT_NGUOI ON dbo.NHANVIEN.NV_NguoiID = dbo.TT_NGUOI.NguoiID 
				  INNER JOIN dbo.CHUCVU ON dbo.NHANVIEN.MaCV = dbo.CHUCVU.MaCV
GO

CREATE VIEW VIEW_KH AS
SELECT dbo.KHACHHANG.KH_NguoiID, dbo.TT_NGUOI.Hoten, dbo.TT_NGUOI.DiaChi, dbo.TT_NGUOI.DienThoai, 
	   dbo.TT_NGUOI.NgaySinh, dbo.TT_NGUOI.CCCD, dbo.TT_NGUOI.GioiTinh
FROM dbo.KHACHHANG INNER JOIN dbo.TT_NGUOI ON dbo.KHACHHANG.KH_NguoiID = dbo.TT_NGUOI.NguoiID

GO
--------------------TRIGGER------------------------
-----Khi nhập kho thì cập nhật số lượng của vật liệu
CREATE TRIGGER TRG_UPDATE_VL ON NHAPKHO
AFTER INSERT AS
BEGIN
	DECLARE @MaVL CHAR(6),@SL INT SELECT @MaVL=MaVL,@SL=SoLuong FROM INSERTED
	UPDATE VATLIEU
	SET SoLuong = SoLuong + @SL
	WHERE MaVL=@MaVL
END

GO
CREATE TRIGGER TRG_UPDATE_VL_2 ON CHITIET_HD
AFTER INSERT AS
BEGIN
	DECLARE @MaCV CHAR(6),@MaVL CHAR(6) SELECT @MaCV=MaCV FROM INSERTED
										SELECT @MAVL=VatLieu FROM CONGVIEC WHERE MaCViec=@MaCV
	UPDATE VATLIEU
	SET SoLuong=SoLuong-1
	WHERE MaVL=@MaVL
END
GO
CREATE TRIGGER TRG_UPDATE_VL_3 ON NHAPKHO
AFTER UPDATE AS
BEGIN
	DECLARE @MaVL CHAR(6),@SL INT SELECT @MaVL=MaVL,@SL=SoLuong FROM INSERTED
	DECLARE @MaVL_DEL CHAR(6),@SL_DEL INT SELECT @MaVL_DEL=MaVL,@SL_DEL=SoLuong FROM deleted
	IF(@MaVL = @MaVL_DEL)
	BEGIN
		UPDATE VATLIEU
		SET SoLuong = SoLuong + @SL - @SL_DEL
		WHERE MaVL=@MaVL
	END
	ELSE
	BEGIN
		UPDATE VATLIEU
		SET SoLuong = SoLuong - @SL_DEL
		WHERE MaVL=@MaVL_DEL
		UPDATE VATLIEU
		SET SoLuong = SoLuong + @SL
		WHERE MaVL=@MaVL
	END
END
GO
CREATE TRIGGER TRG_UPDATE_VL_4 ON CHITIET_HD
AFTER DELETE AS
BEGIN
	DECLARE @SoHD CHAR(15),@MaCV CHAR(6),@MaVL CHAR(6),@NgayNghiemThu DATE 
	SELECT @SoHD=SoHD FROM DELETED
	SELECT @NgayNghiemThu=NgayNghiemThu FROM HOPDONG_BACKUP WHERE SoHD=@SoHD
	SELECT @MaCV=MaCV FROM DELETED
	SELECT @MaVL=VatLieu FROM CONGVIEC WHERE MaCViec=@MaCV
	IF(@NgayNghiemThu is NULL)
	BEGIN
		UPDATE VATLIEU
		SET SoLuong=SoLuong+1
		WHERE MaVL=@MaVL
	END
END
GO
----Tính giá trị của hợp đồng dựa trên các chi tiết hợp đồng
--Tăng giá trị khi thêm một chi tiết

CREATE TRIGGER TRG_UPDATE_HDONG ON CHITIET_HD
AFTER INSERT, UPDATE AS
BEGIN
	DECLARE @SoHD CHAR(15),@TriGiaCV int SELECT @SoHD=SoHD,@TriGiaCV=TriGiaCV FROM INSERTED
	SELECT @TriGiaCV=SUM(TriGiaCV) FROM CHITIET_HD WHERE SoHD=@SoHD
	UPDATE HOPDONG
	SET TriGiaHD = @TriGiaCV
	WHERE SoHD = @SoHD
END
GO
--Giảm giá trị khi xóa một chi tiết

CREATE TRIGGER TRG_UPDATE_HDONG_1 ON CHITIET_HD
AFTER DELETE AS
BEGIN
	DECLARE @SoHD CHAR(15),@TriGiaCV int SELECT @SoHD=SoHD,@TriGiaCV=TriGiaCV FROM DELETED
	UPDATE HOPDONG
	SET TriGiaHD = TriGiaHD - @TriGiaCV
	WHERE SoHD = @SoHD
END
GO
---Tạo login khi thêm một user
CREATE TRIGGER CREATR_LOGIN ON USERS
AFTER INSERT AS
DECLARE @username VARCHAR(20),@pass VARCHAR(20), @chucvu NVARCHAR(30)
SELECT @username = Username, @pass=Pass, @chucvu=ChucVu FROM INSERTED
DECLARE @t NVARCHAR(100)
SET @t = N'CREATE LOGIN ' + QUOTENAME(@Username) + ' WITH PASSWORD = ''' + @Pass +''''
EXEC(@t)
SET @t = N'CREATE USER' + QUOTENAME(@Username) + 'FOR LOGIN' + QUOTENAME(@Username)
EXEC(@t)
IF(@Chucvu=N'Quản lý')
BEGIN
	EXEC sp_addrolemember 'Managers', @Username 
END
ELSE 
BEGIN
	EXEC sp_addrolemember 'Members', @Username 
END
GO
---Sửa login khi thêm một user
CREATE TRIGGER ALTER_LOGIN ON USERS
AFTER UPDATE AS
DECLARE @username VARCHAR(20),@pass VARCHAR(20)
SELECT @username = Username, @pass=Pass FROM INSERTED
DECLARE @t NVARCHAR(100)
SET @t = N'ALTER LOGIN ' + QUOTENAME(@Username) + ' WITH PASSWORD = ''' + @Pass +''''
EXEC(@t)
GO
----Các điều kiện khi thêm hóa đơn
CREATE TRIGGER TRG_INSERT_HOADON ON HOADON
AFTER INSERT AS
DECLARE @SoHD CHAR(15),@TongTien INT,@TriGiaHD INT 
SELECT @SoHD=MaHopDong FROM INSERTED
SELECT @TongTien=sum(SoTienThu) FROM HOADON WHERE MaHopDong=@SoHD
SELECT @TriGiaHD=TriGiaHD FROM HOPDONG WHERE SoHD=@SoHD
IF(@TongTien=@TriGiaHD)----khi giá trị các hóa đơn bằng giá trị hợp đồng thì cập nhật NgayNghiemThu
BEGIN
	UPDATE HOPDONG
	SET NgayNghiemThu=GETDATE()
	WHERE SoHD=@SoHD;
	INSERT INTO HOPDONG_BACKUP
	SELECT *
	FROM HOPDONG
	WHERE HOPDONG.SoHD=@SoHD;

	INSERT INTO CHITIET_HD_BACKUP
	SELECT *
	FROM CHITIET_HD
	WHERE CHITIET_HD.SoHD=@SoHD;

	DELETE HOPDONG WHERE SoHD=@SoHD
END

GO
------Tạo role 
Exec sp_addrole 'Managers'
GO
GRANT EXEC ON XUAT_NV to Managers
GRANT SELECT ON XUAT_NV_CHUCVU to Managers
GRANT SELECT ON TIM_TEN_NV to Managers
GRANT SELECT ON TIM_MS_NV to Managers
GRANT EXEC ON XUAT_KH to Managers
GRANT SELECT ON TIM_TEN_KH to Managers
GRANT SELECT ON TIM_MS_KH to Managers
GRANT EXEC ON XUAT_CHUCVU to Managers
GRANT EXEC ON XUAT_VL to Managers
GRANT SELECT ON TIM_TEN_VL to Managers
GRANT SELECT ON TIM_MS_VL to Managers
GRANT EXEC ON XUAT_NCC to Managers
GRANT SELECT ON TIM_TEN_NCC to Managers
GRANT SELECT ON TIM_MS_NCC to Managers
GRANT SELECT ON XUAT_CVIEC to Managers
GRANT SELECT ON XUAT_HDONG to Managers
GRANT SELECT ON XUAT_NHAPKHO to Managers
GRANT SELECT ON XUAT_NHAPKHO_BACKUP to Managers
GRANT SELECT ON TIM_TG_NHAPKHO to Managers
GRANT SELECT ON TIM_VL_NHAPKHO to Managers
GRANT SELECT ON XUAT_DOANHTHU to Managers
GRANT SELECT ON XUAT_HOADON to Managers
GRANT SELECT ON XUAT_HOPDONG_BACKUP to Managers
GRANT SELECT ON CONGVIEC_CHITIET_HD to Managers
GRANT SELECT ON CONGVIEC_HD to Managers
GRANT SELECT ON TIMKIEM_HDONG to Managers
GO
GRANT EXEC ON THEM_NV to Managers
GRANT EXEC ON THEM_KH to Managers
GRANT EXEC ON THEM_VL to Managers
GRANT EXEC ON THEM_NCC to Managers
GRANT EXEC ON THEM_CVIEC to Managers
GRANT EXEC ON THEM_USER to Managers
GRANT EXEC ON THEM_HDONG to Managers
GRANT EXEC ON THEM_CHITIET_HD to Managers
GRANT EXEC ON THEM_NHAPKHO to Managers
GRANT EXEC ON THEM_HOADON to Managers
GO
GRANT EXEC ON XOA_NV to Managers
GRANT EXEC ON XOA_KH to Managers
GRANT EXEC ON XOA_VL to Managers
GRANT EXEC ON XOA_NCC to Managers
GRANT EXEC ON XOA_CViec to Managers
GRANT EXEC ON XOA_HDONG to Managers
GRANT EXEC ON XOA_CHITIET_HD to Managers
GRANT EXEC ON XOA_NHAPKHO to Managers
GRANT EXEC ON XOA_MONTH_NHAPKHO to Managers
GRANT EXEC ON XOA_DOANHTHU to Managers
GRANT EXEC ON XOA_HOADON to Managers
GO
GRANT EXEC ON SUA_NV to Managers
GRANT EXEC ON SUA_KH to Managers
GRANT EXEC ON SUA_VL to Managers
GRANT EXEC ON SUA_NCC to Managers
GRANT EXEC ON SUA_CViec to Managers
GRANT EXEC ON SUA_USERS to Managers
GRANT EXEC ON SUA_NHAPKHO to Managers
GO
GRANT EXEC ON TIEN_HOADON to Managers
GO
GRANT EXEC ON DOANHTHU to Managers
GRANT EXEC ON TONGTIEN_NHAPKHO to Managers
GRANT SELECT ON XUAT_DOANHTHU to Managers


GO
Exec sp_addrole 'Members'
GO
GRANT EXEC ON XUAT_NV to Members
GRANT SELECT ON XUAT_NV_CHUCVU to Members
GRANT SELECT ON TIM_TEN_NV to Members
GRANT SELECT ON TIM_MS_NV to Members
GRANT EXEC ON XUAT_KH to Members
GRANT SELECT ON TIM_TEN_KH to Members
GRANT SELECT ON TIM_MS_KH to Members
GRANT EXEC ON XUAT_CHUCVU to Members
GRANT EXEC ON XUAT_VL to Members
GRANT SELECT ON TIM_TEN_VL to Members
GRANT SELECT ON TIM_MS_VL to Members
GRANT EXEC ON XUAT_NCC to Members
GRANT SELECT ON TIM_TEN_NCC to Members
GRANT SELECT ON TIM_MS_NCC to Members
GRANT SELECT ON XUAT_CVIEC to Members
GRANT SELECT ON XUAT_HDONG to Members
GRANT SELECT ON XUAT_NHAPKHO to Members
GRANT SELECT ON XUAT_NHAPKHO_BACKUP to Members
GRANT SELECT ON TIM_TG_NHAPKHO to Members
GRANT SELECT ON TIM_VL_NHAPKHO to Members
GRANT SELECT ON XUAT_HOADON to Members
GRANT SELECT ON XUAT_HOPDONG_BACKUP to Members
GRANT SELECT ON CONGVIEC_HD to Members
GRANT SELECT ON CONGVIEC_CHITIET_HD to Managers
GO
GRANT EXEC ON THEM_KH to Members
GRANT EXEC ON THEM_HDONG to Members
GRANT EXEC ON THEM_CHITIET_HD to Members
GRANT EXEC ON THEM_NHAPKHO to Members
GRANT EXEC ON THEM_HOADON to Members
GO
GRANT EXEC ON XOA_KH to Members
GRANT EXEC ON XOA_HDONG to Members
GRANT EXEC ON XOA_CHITIET_HD to Members
GRANT EXEC ON XOA_NHAPKHO to Members
GRANT EXEC ON XOA_MONTH_NHAPKHO to Members
GRANT EXEC ON XOA_HOADON to Members
GO
GRANT EXEC ON SUA_KH to Members
GRANT EXEC ON SUA_NHAPKHO to Members
GO
GRANT SELECT ON TIMKIEM_HDONG to Members
GRANT EXEC ON TIEN_HOADON to Members




